#
# GPL HEADER START
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 only,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License version 2 for more details (a copy is included
# in the LICENSE file that accompanied this code).
#
# You should have received a copy of the GNU General Public License
# version 2 along with this program; If not, see http://www.gnu.org/licenses
#
# Please  visit http://www.xyratex.com/contact if you need additional
# information or have any questions.
#
# GPL HEADER END
#
# Copyright 2017 Seagate Technology LLC
#
# Author: Roman Grigoryev<Roman.Grigoryev@seagate.com>
#

=pod

=head1 NAME

Xperior::Executor::Roles::CopytoolLogCollector - Role collects
copytool logs which generated by lustre t-f.sh

=head1 DESCRIPTION


Lustre hsm suite generates '.*copytool.*' files in lustre test workdir.
Algorithm is:
1. parsing test stdout and searching
    Logging to local directory: <path>
    Start copytool
2. if substrings found collect .*copytool.* files from work directory and
attach to test results



=cut

package Xperior::Executor::Roles::CopytoolLogCollector;
use strict;
use warnings;
use Moose::Role;
use Data::Dumper;
use Log::Log4perl qw(:easy);
use Xperior::RemoteHelper;

my $title = 'CopytoolLogCollector';
has executeutils  => ( is => 'rw');

after 'execute' => sub {
    my $self = shift;
    $self->beforeAfterExecute($title);
    my $filename = $self->getNormalizedLogName('stdout');
    DEBUG("Open log file [$filename]");
    open( F, "  $filename" );
    my $copytool = 0;
    my $path = '';
    while ( defined( my $s = <F> ) ) {
        chomp $s;
        if( $s =~ m/Start\scopytool/ ){
            $copytool = 1;
        }elsif( $s =~ m/Logging\s+to\s+local\s+directory:\s+(\S+)/ ){
            $path = $1;
            DEBUG "Found t-f.sh workdir path [$1]";
        }
        if( $copytool and $path ) {
            DEBUG "Collecting logs from [$path]";
            my $mclient    = $self->_getMasterNode();
            my $mclientobj = $self->env->getNodeById($mclient->{'node'});
            my @files = ("$path/*copytool*");
            collect_remote_files_by_mask($mclientobj , $self, \@files);
            last;
        }
    }
     close( F );
    $self->afterAfterExecute($title);
};

1;

=head1 COPYRIGHT AND LICENSE

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License version 2 only,
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License version 2 for more details (a copy is included
in the LICENSE file that accompanied this code).

You should have received a copy of the GNU General Public License
version 2 along with this program; If not, see http://www.gnu.org/licenses



Copyright 2017 Seagate Technology LLC

=head1 AUTHOR

Roman Grigoryev<Roman.Grigoryev@seagate.com>

=cut
