#
# GPL HEADER START
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 only,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License version 2 for more details (a copy is included
# in the LICENSE file that accompanied this code).
#
# You should have received a copy of the GNU General Public License
# version 2 along with this program; If not, see http://www.gnu.org/licenses
#
# Please  visit http://www.xyratex.com/contact if you need additional information or
# have any questions.
#
# GPL HEADER END
#
# Copyright 2012 Xyratex Technology Limited
#
# Author: Roman Grigoryev<Roman_Grigoryev@xyratex.com>
#

=pod

=head1 Xperior harness developer guide

System created on Perl language, with wide using additional modules from CPAN.

=head2 Structure of /opt/xyratex/xperior/lib folder

=over

=item *

Xperior - main classes and libraries are stored there

=item *

Xperior::Executor - wrappers for specific tests are store there

=back

=head2 Class diagram


=for html <hr> <img src="classes.png">
<p> This is a raw HTML paragraph </p>

=head2 How run tests and configure node for run them

This order is suggested for test execution.

=head3 Tests which doesn't need configurations

=over 5

=item t/executors.t

=item t/utils.t

=item t/core.t

=item t/checkyaml.t

=item t/compatlustretests.t

=back

=head3 Test which need basic configuration

First group need simple configuration and check base for second group.

These tests need:

- user 'tomcat' and passwordless login to it from user which run tests on local host

=over 4

=item t/sshprocess.t

=item t/launcher.t

=item t/ielists.t

=item t/lustresingleexec.t

=item t/roleStoreSyslog.t

=back

=head3 Tests which need distributed configuration

These tests need virtual machines with specific lustre setup and password less sudo.

=over 1

=item t/kvmnode.t
need only one kvm node which called mds and passwordless sudo

=back

=head3 Test which need very specific configuration which should not be used until developer provides his own setup

=over

=item ipminode.t

The test needs node which have IPMI and which could be safely rebooted

=back

=head2 See also

L<http://en.wikipedia.org/wiki/Test_Anything_Protocol>

L<http://www.yaml.org/>

L<http://cpan.org>

=cut
